services:
  - type: web
    name: securechat-backend
    env: node
    region: oregon
    branch: main
    rootDir: server
    buildCommand: npm install
    startCommand: node app.mjs
    envVars:
      - key: USE_HTTPS
        value: false